//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public int Unit { get; set; }
        public int UnitPrice { get; set; }
        public int Vat { get; set; }
        public int SupplierId { get; set; }
        public int ManufacturerId { get; set; }
        public int ProductTypeID { get; set; }
    
        public virtual MANUFACTURER MANUFACTURER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
